force-app/main/default/objects/litify_pm__Intake__c/fields/Call_at_Date__c.field-meta.xml
<CustomField>
    <fullName>Call_at_Date__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Appointment_Date__c)) &amp;&amp; NOT(ISBLANK(Follow_Up_Date_Time__c)),
  IF(
    Appointment_Date__c &gt;= Follow_Up_Date_Time__c,
    Appointment_Date__c,
    Follow_Up_Date_Time__c
  ),
  IF(
    NOT(ISBLANK(Appointment_Date__c)),
    Appointment_Date__c,
    IF(
      NOT(ISBLANK(Follow_Up_Date_Time__c)),
      Follow_Up_Date_Time__c,
      CreatedDate
    )
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Call at Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Case_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Priority_Score__c.field-meta.xml
<CustomField>
    <fullName>Priority_Score__c</fullName>
    <formula>(CASE(litify_pm__Status__c, 
         &apos;Lead Generated&apos;, 1,
         &apos;Intake Scheduled&apos;, 2, 
         &apos;In Contact/Under Review&apos;, 3,
         &apos;Missed Appointment&apos;, 4,
         &apos;Intake Package Sent&apos;, 5,
         &apos;Attempting to Contact&apos;, 6,
         &apos;Questionnaire&apos;, 7,
         99) * 10) + 
       CASE(Case_Type_Reporting__c,
         &apos;Labor Law&apos;, 1,
         &apos;MVA&apos;, 2,
         &apos;Premises&apos;, 3,
         &apos;WC &amp; PI&apos;, 4,
         &apos;Personal Injury&apos;, 5,
         &apos;Worker Compensation&apos;, 6,
         7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Qualification_Status__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Status__c</fullName>
    <label>Qualification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Queue_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Queue_Case_Type__c</fullName>
    <label>Queue Case Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Referred_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Referred_By_Name__c</fullName>
    <formula>Referred_By__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Referred By Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Test_Record__c.field-meta.xml
<CustomField>
    <fullName>Test_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if this is a test record</inlineHelpText>
    <label>Test Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/litify_pm__Intake__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomIntakeTriggerHandler.cls
public class CustomIntakeTriggerHandler {

    public static void handleTrigger() {
        LeadQueueLogging.debug('=== CUSTOM_TRIGGER_DEBUG: CustomIntakeTriggerHandler called - isBefore: ' + Trigger.isBefore + ', isAfter: ' + Trigger.isAfter + ', isUpdate: ' + Trigger.isUpdate + ' ===');
        
        if (Trigger.isBefore) {
            if (Trigger.isInsert) {
                handleBeforeInsert((List<litify_pm__Intake__c>) Trigger.new);
            }
            else if (Trigger.isUpdate) {
                handleBeforeUpdate((List<litify_pm__Intake__c>) Trigger.new, Trigger.oldMap);
            }
            else if (Trigger.isDelete) {
                handleBeforeDelete((List<litify_pm__Intake__c>) Trigger.old);
            }
        }
        
        if (Trigger.isAfter) {
            if (Trigger.isInsert) {
                handleAfterInsert((List<litify_pm__Intake__c>) Trigger.new);
            }
            else if (Trigger.isUpdate) {
                handleAfterUpdate((List<litify_pm__Intake__c>) Trigger.new, Trigger.oldMap);
            }
            else if (Trigger.isDelete) {
                handleAfterDelete((List<litify_pm__Intake__c>) Trigger.old);
            }
            else if (Trigger.isUndelete) {
                handleAfterUndelete((List<litify_pm__Intake__c>) Trigger.new);
            }
        }
    }
    
    private static void handleBeforeInsert(List<litify_pm__Intake__c> newRecords) {
        applyQueuePriority(newRecords);
    }
    
    private static void handleBeforeUpdate(List<litify_pm__Intake__c> newRecords, Map<Id, SObject> oldRecordsMap) {
        applyQueuePriority(newRecords);
    }
    
    private static void handleBeforeDelete(List<litify_pm__Intake__c> oldRecords) {
        // Add before delete logic here
    }
    
    private static void handleAfterInsert(List<litify_pm__Intake__c> newRecords) {
        LeadQueueRefreshPublisher.publish('intake-insert');
    }
    
    private static void handleAfterUpdate(List<litify_pm__Intake__c> newRecords, Map<Id, SObject> oldRecordsMap) {
        // Route to specific modules
        Map<Id, litify_pm__Intake__c> typedOldMap = (Map<Id, litify_pm__Intake__c>) oldRecordsMap;
        LeadQueueService.handleIntakeFieldChanges(newRecords, typedOldMap);
        if (shouldPublishQueueRefresh(newRecords, typedOldMap)) {
            LeadQueueRefreshPublisher.publish('intake-update');
        }
    }
    
    private static void handleAfterDelete(List<litify_pm__Intake__c> oldRecords) {
        LeadQueueRefreshPublisher.publish('intake-delete');
    }
    
    private static void handleAfterUndelete(List<litify_pm__Intake__c> newRecords) {
        LeadQueueRefreshPublisher.publish('intake-undelete');
    }

    private static Boolean shouldPublishQueueRefresh(List<litify_pm__Intake__c> newRecords, Map<Id, litify_pm__Intake__c> oldRecordsMap) {
        if (newRecords == null || oldRecordsMap == null) {
            return false;
        }
        for (litify_pm__Intake__c newRecord : newRecords) {
            litify_pm__Intake__c oldRecord = oldRecordsMap.get(newRecord.Id);
            if (oldRecord == null) {
                continue;
            }
            if (hasQueueRelevantChange(newRecord, oldRecord)) {
                return true;
            }
        }
        return false;
    }

    private static Boolean hasQueueRelevantChange(litify_pm__Intake__c newRecord, litify_pm__Intake__c oldRecord) {
        return newRecord.litify_pm__Status__c != oldRecord.litify_pm__Status__c
            || newRecord.Priority_Score__c != oldRecord.Priority_Score__c
            || newRecord.Queue_Case_Type__c != oldRecord.Queue_Case_Type__c
            || newRecord.Call_at_Date__c != oldRecord.Call_at_Date__c
            || newRecord.litify_pm__Sign_Up_Method__c != oldRecord.litify_pm__Sign_Up_Method__c
            || newRecord.Qualification_Status__c != oldRecord.Qualification_Status__c
            || newRecord.Test_Record__c != oldRecord.Test_Record__c
            || newRecord.Type__c != oldRecord.Type__c
            || newRecord.litify_pm__Display_Name__c != oldRecord.litify_pm__Display_Name__c
            || newRecord.Referred_By_Name__c != oldRecord.Referred_By_Name__c
            || newRecord.litify_pm__Phone__c != oldRecord.litify_pm__Phone__c
            || newRecord.Name != oldRecord.Name;
    }

    private static void applyQueuePriority(List<litify_pm__Intake__c> records) {
        for (litify_pm__Intake__c record : records) {
            String queueCaseType = LeadQueueConfig.normalizeCaseType(record.Type__c, record.Case_Type__c);
            Integer caseTypePriority = LeadQueueConfig.getCaseTypePriority(queueCaseType);
            record.Queue_Case_Type__c = queueCaseType;
            record.Priority_Score__c = LeadQueueConfig.calculatePriorityScore(record.litify_pm__Status__c, caseTypePriority);
        }
    }
}